---

- name: Lynis | Debian | install support for APT thru HTTPS
  apt:
    name: apt-transport-https
    state: present

- name: Lynis | Debian | install lynis official repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C80E383C3DE9F082E01391A0366C67DE91CA5D5F

- name: Lynis | Debian | add lynis official repo
  copy:
    content: "deb https://packages.cisofy.com/community/lynis/deb/ {{ ansible_lsb.codename }} main"
    dest: "/etc/apt/sources.list.d/cisofy-lynis.list"
    owner: root
    group: root
    mode: 0644

- name: Lynis | Debian | install lynis package
  apt:
    name: lynis
    state: present
    update_cache: yes
