---
- name: Lynis | Fedora | update prerequisites
  dnf:
    name:
        - ca-certificates
        - curl
        - nss
        - openssl
    state: present

- name: Lynis | Fedora | add lynis official repo
  yum_repository:
    name: lynis
    description: CISOfy Software - Lynis package
    baseurl: https://packages.cisofy.com/community/lynis/rpm/
    enabled: yes
    gpgkey: https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
    gpgcheck: yes

- name: Lynis | Fedora | install lynis package
  dnf:
    name: lynis
    state: present
