---
# tasks file for mablanco.lynis

- name: Lynis | lynis_report_from should be defined
  ansible.builtin.assert:
    that:
      - lynis_report_from is defined and lynis_report_from | length > 0
    msg: "Set the value of 'lynis_report_from' in either the inventory file or the playbook invoking this role."

- name: Lynis | lynis_report_to should be defined
  ansible.builtin.assert:
    that:
      - lynis_report_to is defined and lynis_report_to | length > 0
    msg: "Set the value of 'lynis_report_to' in either the inventory file or the playbook invoking this role."

- name: Lynis | create lynis home
  ansible.builtin.file:
    path: "{{ lynis_home }}"
    mode: 0750
    owner: root
    group: root
    state: directory
  when: lynis_deploy_method in [ "tar", "git" ]

- name: Lynis | install git cli client
  ansible.builtin.package:
    name: git
    state: present
  when: lynis_deploy_method == "git"

- name: Lynis | deploy lynis with git
  ansible.builtin.git:
    repo: "{{ lynis_git_repo }}"
    clone: true
    dest: "{{ lynis_home }}"
    force: true
    version: "master"
  when: lynis_deploy_method == "git"

- name: Lynis | deploy lynis with tar
  include: tar.yml
  when: lynis_deploy_method == "tar"

- name: Lynis | deploy lynis with distro package
  include: pkg.yml
  when: lynis_deploy_method == "pkg"

- name: Lynis | create man page directory
  ansible.builtin.file:
    path: /usr/local/share/man/man8/
    mode: 0755
    owner: root
    group: root
    state: directory
  when: lynis_deploy_method in [ "tar", "git" ]

- name: Lynis | install man page
  ansible.builtin.copy:
    src: "{{ lynis_home }}/lynis.8"
    dest: "/usr/local/share/man/man8/"
    mode: 0644
    owner: root
    group: root
    remote_src: true
  when: lynis_deploy_method in [ "tar", "git" ]

- name: Lynis | create lynis etc directory
  ansible.builtin.file:
    path: /etc/lynis
    mode: 0750
    owner: root
    group: root
    state: directory
  when: lynis_deploy_method in [ "tar", "git" ]

# - name: Lynis | Copy default.prf to /etc/lynis
#   ansible.builtin.copy:
#     src: /opt/lynis/default.prf
#     dest: /etc/lynis/default.prf

- name: Lynis | install custom profile
  ansible.builtin.template:
    src: lynis.custom.prf.j2
    dest: /etc/lynis/custom.prf
    owner: root
    group: root
    mode: '0640'
  when: lynis_deploy_method in [ "tar", "git", "pkg" ]

- name: Lynis | create lynis log directory
  ansible.builtin.file:
    path: /var/log/lynis
    mode: 0750
    owner: root
    group: root
    state: directory

- name: Lynis | install cron job
  ansible.builtin.template:
    src: lynis.cron.j2
    dest: /usr/local/bin/lynis_cron.sh
    owner: root
    group: root
    mode: 0750

- name: Lynis | schedule weekly audit
  ansible.builtin.cron:
    name: "Launch Lynis security audit"
    minute: "{{ lynis_cron_minute }}"
    hour: "{{ lynis_cron_hour }}"
    day: "{{ lynis_cron_day }}"
    month: "{{ lynis_cron_month }}"
    weekday: "{{ lynis_cron_dow }}"
    cron_file: "lynis"
    user: "root"
    job: "/usr/local/bin/lynis_cron.sh 2>&1 | logger"
