---
# tasks file for mablanco.lynis

- name: Lynis | lynis_report_from should be defined
  assert:
    that:
    - lynis_report_from is defined and lynis_report_from != ''
    msg: "Set the value of 'lynis_report_from' in either the inventory file or the playbook invoking this role."

- name: Lynis | lynis_report_to should be defined
  assert:
    that:
    - lynis_report_to is defined and lynis_report_to != ''
    msg: "Set the value of 'lynis_report_to' in either the inventory file or the playbook invoking this role."

- name: Lynis | create lynis home
  file:
    path: "{{ lynis_home }}"
    mode: 0750
    owner: root
    group: root
    state: directory
  when: lynis_deploy_method in [ "tar", "git" ]

- name: Lynis | install git cli client
  package:
    name: git
    state: present
  when: lynis_deploy_method == "git"

- name: Lynis | deploy lynis with git
  git:
    repo: "{{ lynis_git_repo }}"
    clone: yes
    dest: "{{ lynis_home }}"
    force: yes
  when: lynis_deploy_method == "git"

- name: Lynis | deploy lynis with tar
  include: tar.yml
  when: lynis_deploy_method == "tar"

- name: Lynis | deploy lynis with distro package
  include: pkg.yml
  when: lynis_deploy_method == "pkg"

- name: Lynis | create man page directory
  file:
    path: /usr/local/share/man/man8/
    mode: 0755
    owner: root
    group: root
    state: directory
  when: lynis_deploy_method in [ "tar", "git" ]

- name: Lynis | install man page
  copy:
    src: "{{ lynis_home }}/lynis.8"
    dest: "/usr/local/share/man/man8/"
    mode: 0644
    owner: root
    group: root
    remote_src: true
  when: lynis_deploy_method in [ "tar", "git" ]

- name: Lynis | create lynis etc directory
  file:
    path: /etc/lynis
    mode: 0750
    owner: root
    group: root
    state: directory
  when: lynis_deploy_method in [ "tar", "git" ]

- name: Lynis | install custom profile
  template:
    src: lynis.custom.prf.j2
    dest: /etc/lynis/custom.prf
    owner: root
    group: root
    mode: 0640
  when: lynis_deploy_method in [ "tar", "git", "pkg" ]

- name: Lynis | create lynis log directory
  file:
    path: /var/log/lynis
    mode: 0750
    owner: root
    group: root
    state: directory

- name: Lynis | install cron job
  template:
    src: lynis.cron.j2
    dest: /usr/local/bin/lynis_cron.sh
    owner: root
    group: root
    mode: 0750

- name: Lynis | schedule weekly audit
  cron:
    name: "Launch Lynis security audit"
    hour: "{{ lynis_cron_hour }}"
    minute: "{{ lynis_cron_minute }}"
    weekday: "{{ lynis_cron_dow }}"
    cron_file: "lynis"
    user: "root"
    job: "/usr/local/bin/lynis_cron.sh 2>&1 | logger"
