---

- name: Lynis | RedHat | update prerequisites
  yum:
    name: {{ item }}
    state: present
  with_items:
  - ca-certificates
  - curl
  - nss
  - openssl

- name: Lynis | RedHat | add lynis official repo
  yum_repository:
    name: lynis
    description: CISOfy Software - Lynis package
    baseurl: https://packages.cisofy.com/community/lynis/rpm/
    enabled: yes
    gpgkey: https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
    gpgcheck: yes

- name: Lynis | RedHat | install lynis package
  yum:
    name: lynis
    state: present
    update_cache: yes
