---

- name: Lynis | RedHat | update prerequisites
  yum:
    name:
      - ca-certificates
      - curl
      - nss
      - openssl
    state: present

- name: Lynis | RedHat | add lynis official repo
  yum_repository:
    name: lynis
    description: CISOfy Software - Lynis package
    baseurl: https://packages.cisofy.com/community/lynis/rpm/
    enabled: true
    gpgkey: https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
    gpgcheck: true

- name: Lynis | RedHat | install lynis package
  yum:
    name: lynis
    state: present
    update_cache: true
