---

- name: Lynis | SuSE | install lynis official repo key
  rpm_key:
    key: https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
    validate_certs: false
    state: present

- name: Lynis | SuSE | add lynis official repo
  zypper_repository:
    name: lynis
    description: CISOfy Lynis repository
    repo: 'https://packages.cisofy.com/community/lynis/rpm/'
    state: present

- name: Lynis | SuSE | install lynis package
  zypper:
    name: lynis
    state: present
