---

- name: Lynis | tar | extract archive
  unarchive:
    src: "{{ lynis_url }}/{{ lynis_package }}"
    dest: "{{ lynis_home }}"
    remote_src: yes
    owner: root
    group: root
    extra_opts: [--strip-components=1]
