---

- name: deploy lynis with tar (download)
  get_url:
    url: "{{ lynis_url }}/{{ lynis_package }}"
    dest: "{{ lynis_download_dir }}/{{ lynis_package }}"
    checksum: "{{ lynis_package_checksum }}"
    validate_certs: no

- name: deploy lynis with tar (extract)
  unarchive:
    src: '{{ lynis_download_dir }}/{{ lynis_package }}'
    dest: '{{ lynis_home }}/..'
    copy: no

- name: deploy lynis with tar (delete package)
  file:
    path: '{{ lynis_download_dir }}/{{ lynis_package }}'
    state: absent
